const ROTARACT_CLUBS = [
  'Rotaract Club of A.C. Tech',
  'Rotaract Club of A.M. Jain College - Shift I',
  'Rotaract Club of A.M. Jain College - Shift II',
  'Rotaract Club of Agni College of Technology',
  'Rotaract Club of Ambattur',
  'Rotaract Club of AMET University',
  'Rotaract Club of Anna Adarsh',
  'Rotaract Club of Asan Memorial College of Arts & Science',
  'Rotaract Club of Asan Memorial College of Engineering and Technology',
  'Rotaract Club of AVIT',
  'Rotaract Club of Bhaktavatsalam Memorial College for Women',
  'Rotaract Club of Chennai',
  'Rotaract Club of Chennai Bliss',
  'Rotaract Club of Chennai Central',
  'Rotaract Club of Chennai Dynamic Entrepreneurs',
  'Rotaract Club of Chennai Gems',
  'Rotaract Club of Chennai Genesis',
  'Rotaract Club of Chennai Legends',
  'Rotaract Club of Chennai Premier',
  'Rotaract Club of Chennai Shakthi',
  'Rotaract Club of Coastal Legacy',
  'Rotaract Club of College of Engineering, Guindy',
  'Rotaract Club of D G Vaishnav College',
  'Rotaract Club of D.R.B.C.C.C. Hindu College',
  'Rotaract Club of Dhanalakshmi College of Engineering',
  'Rotaract Club of Dr. MGR Janaki College of Arts and Science for Women',
  'Rotaract Club of Dream Home',
  'Rotaract Club of Drishti',
  'Rotaract Club of Ethiraj College for Women',
  'Rotaract Club of GSS Jain College for Women',
  'Rotaract Club of Hindustan College of Arts and Science',
  'Rotaract Club of Jeppiaar University',
  'Rotaract Club of Jeppiar Engineering College',
  'Rotaract Club of Jerusalem College of Engineering',
  'Rotaract Club of Kings Cornerstone International College',
  'Rotaract Club of Kumararani Meena Muthiah College of Arts and Science',
  'Rotaract Club of Loyola College',
  'Rotaract Club of M.O.P. Vaishnav College for Women',
  'Rotaract Club of Madras',
  'Rotaract Club of Madras Central',
  'Rotaract Club of Madras East',
  'Rotaract Club of Madras Gold Coast',
  'Rotaract Club of Madras Knights',
  'Rotaract Club of Madras Millennia',
  'Rotaract Club of Madras Rhythms',
  'Rotaract Club of Madras Steps',
  'Rotaract Club of Mahalakshmi College of Arts and Science',
  'Rotaract Club of Mohamed Sathak College of Arts and Science',
  'Rotaract Club of Nanganallur Elite',
  'Rotaract Club of New College',
  'Rotaract Club of Panimalar Medical College',
  'Rotaract Club of Prince Shri Venkateshwara Arts and Science College',
  'Rotaract Club of S.A. College of Arts and Science',
  'Rotaract Club of S.I.V.E.T. College',
  'Rotaract Club of S.R.M. Easwari Engineering College',
  'Rotaract Club of Sagaa',
  'Rotaract Club of Saveetha Dental College',
  'Rotaract Club of Saveetha School of Management',
  'Rotaract Club of SDNB Vaishnav College',
  'Rotaract Club of Shree Muthukumaraswamy College',
  'Rotaract Club of Spectrum',
  'Rotaract Club of Sri Venkateswara College of Engineering',
  'Rotaract Club of SRMKTR',
  'Rotaract Club of SSS Shasun Jain College for Women',
  'Rotaract Club of St. Anne\'s Arts and Science College',
  'Rotaract Club of Stella Maris College',
  'Rotaract Club of Tagore Dental College',
  'Rotaract Club of Tamilnadu Dr. Ambedkar Law University',
  'Rotaract Club of TJS College of Arts and Science',
  'Rotaract Club of VELS Institute of Science, Technology & Advanced Studies',
  'Rotaract Club of Vepery',
  'Rotaract Club of Vishwahita',
  'Rotaract Club of VIT Chennai',
  'Rotaract Club of Women\'s Christian College',
  'Rotaract Club of YMCA',
  'Rotaract Club of Youth Organ Donation Awareness',
];

module.exports = { ROTARACT_CLUBS };
